# -*- coding: utf-8 -*-
"""Cruise Controller.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aoSsiJLdF-Vi7T5YxV3Rr8hfsC4a-JbZ
"""

import math
import matplotlib.pyplot as plt
m=500
c=10
r=60
v=0
sample_time=1
k_p=120
k_i=2.5
k_d=2
e_i=0
e_old=14
velocity=[0]
time=[i for i in range(60)]




for i in range(59):

    t=i
    e=r-v
    e_i+=e
    e_d=e-e_old
    u=k_p*e+k_i*e_i+k_d*e_d
    v_new=(u-c*v)/m+v
    e_old=e 
    velocity.append(v_new)
    v=v_new
    
    
    


plt.plot(time,velocity)

plt.xlabel('time')
plt.ylabel('velocity')
plt.plot(time,velocity,label="reference velocity is 60 km/hr")
plt.legend()
plt.show()